version: "3.7"
services:
  app:
    container_name: "date-picker"
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/share/app
    environment:
      ENV: "develop"
    volumes:
      - .:/usr/share/app
      - /usr/share/app/node_modules
    ports:
      - "8080:80"
